<?php

/**
 * @link http://www.re-soft.de
 * @copyright Copyright (c) Tobias Streckel
 * @license MIT
 */

namespace strtob\yii2GridviewColumns;

use Yii;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\grid\Column;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\ActiveQueryInterface;
use yii\base\Model;

/**
 * Class AmountColumn
 * 
 * This class provides a custom column type for Yii2 GridView to display formatted amounts.
 * It includes additional features such as color-coding, badges, and footer sum calculations.
 */
class AmountColumn extends Column
{
    private const VALUE_DEFAULT = 1;

    /**
     * {@inheritdoc}
     */
    public $headerOptions = ['class' => 'amount-column'];

    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     * If [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    public $attribute;

    /**
     * @var mixed the value of the column. Can be a closure or a property.
     */
    public $value;

    /**
     * @var bool Whether to show the footer sum for this column.
     */
    public $showFooterSum = true;

    /**
     * @var mixed Custom footer value. Can be a closure or a fixed value.
     */
    public $footerValue;

    /**
     * @var string|null The label for the column. If not set, the label associated with the attribute will be displayed.
     */
    public $label;

    /**
     * @var int The number of decimal places to format the value with.
     */
    public $decimals = 2;

    /**
     * @var string A prefix to be added before the value.
     */
    public $prefix = '';

    /**
     * @var string A suffix to be added after the value.
     */
    public $suffix = '';

    /**
     * @var string The suffix to be added in the footer.
     */
    public $footerSuffix = '';

    /**
     * @var bool If true, shows positive values in green and negative values in red.
     */
    public $badge = false;

    /**
     * @var string Additional class for the badge, e.g., 'fa-1x'.
     */
    public $additionalBadgeClass = 'fa-1x';

    /**
     * @var bool If true, shows positive values in green and negative values in red using text coloring.
     */
    public $colored = true;

    /**
     * @var bool Whether the header label should be HTML-encoded.
     * @see label
     * @since 2.0.1
     */
    public $encodeLabel = true;

    /**
     * @var int A specific value, defaulting to 1.
     */
    public $stateValue = self::VALUE_DEFAULT;

    /**
     * @var bool Whether to allow sorting by this column. If true and [[attribute]] is found in
     * the sort definition of [[GridView::dataProvider]], the header cell of this column will contain
     * a link to trigger sorting when clicked.
     */
    public $enableSorting = true;

    /**
     * @var array The HTML attributes for the link tag in the header cell generated by [[\yii\data\Sort::link]]
     * when sorting is enabled for this column.
     */
    public $sortLinkOptions = [];

    /**
     * {@inheritdoc}
     */
    protected function renderHeaderCellContent()
    {
        if ($this->header !== null || ($this->label === null && $this->attribute === null)) {
            return parent::renderHeaderCellContent();
        }

        $label = $this->getHeaderCellLabel();

        if ($this->encodeLabel) {
            $label = Html::encode($label);
        }

        if (
            $this->attribute !== null && $this->enableSorting &&
            ($sort = $this->grid->dataProvider->getSort()) !== false && $sort->hasAttribute($this->attribute)
        ) {
            return $sort->link($this->attribute, array_merge($this->sortLinkOptions, ['label' => $label]));
        }

        return $label;
    }

    /**
     * Gets the label for the header cell based on the data provider and model attributes.
     *
     * @return string
     * @since 2.0.8
     */
    protected function getHeaderCellLabel()
    {
        $provider = $this->grid->dataProvider;

        if ($this->label === null) {
            if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface) {
                $modelClass = $provider->query->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($provider instanceof ArrayDataProvider && $provider->modelClass !== null) {
                $modelClass = $provider->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($this->grid->filterModel !== null && $this->grid->filterModel instanceof Model) {
                $label = $this->grid->filterModel->getAttributeLabel($this->attribute);
            } else {
                $models = $provider->getModels();
                if (($model = reset($models)) instanceof Model) {
                    $label = $model->getAttributeLabel($this->attribute);
                } else {
                    $label = Inflector::camel2words($this->attribute);
                }
            }
        } else {
            $label = $this->label;
        }

        return $label;
    }

    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $value = $this->value instanceof \Closure ? call_user_func($this->value, $model, $index) : $model->{$this->attribute};

        $suffix = $this->suffix instanceof \Closure ? call_user_func($this->suffix, $model, $index) : $this->suffix;

        return $this->formatResult($value, $suffix);
    }

    /**
     * {@inheritdoc}
     */
    protected function renderFooterCellContent()
    {
        if ($this->showFooterSum) {
            $dataProvider = $this->grid->dataProvider;
            $models = $dataProvider->getModels();

            $sum = 0;

            // Closure for footer cell content
            if ($this->footerValue instanceof \Closure) {
                $sum = call_user_func($this->footerValue, $models);
            } else {
                foreach ($models as $model) {
                    $value = $model->{$this->attribute} ?? 0;
                    $sum += $value;
                }
            }

            $suffix = $this->footerSuffix instanceof \Closure ? call_user_func($this->footerSuffix, $models) : $this->footerSuffix;

            return $this->formatResult($sum, $suffix);
        }

        return parent::renderFooterCellContent();
    }

    /**
     * Formats the result with prefix, suffix, and optionally colored/badge display.
     *
     * @param mixed $value The value to format.
     * @param string $suffix The suffix to append.
     * @param mixed|null $model The data model (optional).
     * @return string The formatted result.
     */
    private function formatResult($value, $suffix = '', $model = null)
    {
        $result = Yii::$app->formatter->asDecimal($value, $this->decimals);

        if ($this->colored) {
            $badgeClass = 'success';
            if ($value < 0) {
                $badgeClass = 'danger';
            } elseif ($value == 0) {
                $badgeClass = 'primary';
            }

            $badgeHtml = ($this->prefix !== '' ? $this->prefix . ' ' : '') . $result . ' ' . $suffix;
            if ($this->badge) {
                return '<span class="' . trim('badge badge-outline-' . $badgeClass . ' ' . $this->additionalBadgeClass) . '">' . $badgeHtml . '</span>';
            } else {
                return '<span class="text-' . $badgeClass . '">' . $badgeHtml . '</span>';
            }
        }

        return ($this->prefix !== '' ? $this->prefix . ' ' : '') . $result . ' ' . $suffix;
    }
}
