<?php
/**
 * @link http://www.re-soft.de
 * @copyright Copyright (c) Tobias Streckel
 * @license MIT
 */

namespace strtob\yii2GridviewColumns;

use Yii;

use kartik\grid\DataColumn;
use yii\helpers\Html;
use yii\helpers\Inflector;

use kartik\grid\GridView;

class BooleanColumn extends \kartik\grid\DataColumn{

    private const VALUE_DEFAULT = 1;

    public const VALUE_ON_OFF = 1;

    public const VALUE_ACTIVE_OFF = 2;

    public const VALUE_SUCCESS_ERROR = 3;

    public const VALUE_TRUE_FALSE = 4;
    
    public const VALUE_GRANTED_BLOCKED = 5;
    
    public const VALUE_NULL_ERROR = 6;

    /**
     * {@inheritdoc}
     */
    public $headerOptions = ['class' => 'boolean-column'];

    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     *
     * Also, if [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    public $attribute;

    /**
     * @var string label to be displayed in the [[header|header cell]] and also to be used as the sorting
     * link label when sorting is enabled for this column.
     * If it is not set and the models provided by the GridViews data provider are instances
     * of [[\yii\db\ActiveRecord]], the label will be determined using [[\yii\db\ActiveRecord::getAttributeLabel()]].
     * Otherwise [[\yii\helpers\Inflector::camel2words()]] will be used to get a label.
     */
    public $label;

    /**
     * @var bool whether the header label should be HTML-encoded.
     * @see label
     * @since 2.0.1
     */
    public $encodeLabel = true;

    /**
     * @var Specific Text; Default = 1
     */
    public $stateValue = self::VALUE_DEFAULT;


    /**
     * @var bool whether to allow sorting by this column. If true and [[attribute]] is found in
     * the sort definition of [[GridView::dataProvider]], then the header cell of this column
     * will contain a link that may trigger the sorting when being clicked.
     */
    public $enableSorting = true;

    /**
     * @var array the HTML attributes for the link tag in the header cell
     * generated by [[\yii\data\Sort::link]] when sorting is enabled for this column.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $sortLinkOptions = [];


    /**
     * @inheritdoc
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {

      $arrType = array();

     
        switch ($this->stateValue) {
            case 1:
              $arrType = [Yii::t('app_sys', 'OFF'), Yii::t('app_sys', 'ON')];
              break;
            case 2:
              $arrType = [Yii::t('app_sys', 'OFF'), Yii::t('app_sys', 'ACTIVE')];
              break;
            case 3:
              $arrType = [Yii::t('app_sys', 'ERROR'), Yii::t('app_sys', 'SUCCESS')];
              break;
            case 4:
              $arrType = [Yii::t('app_sys', 'FALSE'), Yii::t('app_sys', 'TRUE')];
              break;
            case 5:
              $arrType = [Yii::t('app_sys', 'GRANTED'), Yii::t('app_sys', 'BLOCKED')];
              break;
            case 6:
              $arrType = [Yii::t('app_sys', ''), 'ERROR'];
              break;
        }

      $this->filterType = GridView::FILTER_SELECT2;
      
      $this->filter = $arrType;
      $this->filterWidgetOptions = ['pluginOptions' => ['allowClear' => true]];
      $this->filterInputOptions  = ['placeholder' => '', 'id' => 'grid-search-' . $this->attribute];
      parent::init();

    }

    /**
     * {@inheritdoc}
     */
    protected function renderHeaderCellContent()
    {
        if ($this->header !== null || $this->label === null && $this->attribute === null) {
            return parent::renderHeaderCellContent();
        }

        $label = $this->getHeaderCellLabel();
        if ($this->encodeLabel) {
            $label = Html::encode($label);
        }

        if ($this->attribute !== null && $this->enableSorting &&
            ($sort = $this->grid->dataProvider->getSort()) !== false && $sort->hasAttribute($this->attribute)) {
            return $sort->link($this->attribute, array_merge($this->sortLinkOptions, ['label' => $label]));
        }

        return $label;
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    protected function getHeaderCellLabel()
    {
        $provider = $this->grid->dataProvider;

        if ($this->label === null) {
            if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface) {
                /* @var $modelClass Model */
                $modelClass = $provider->query->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($provider instanceof ArrayDataProvider && $provider->modelClass !== null) {
                /* @var $modelClass Model */
                $modelClass = $provider->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($this->grid->filterModel !== null && $this->grid->filterModel instanceof Model) {
                $label = $this->grid->filterModel->getAttributeLabel($this->filterAttribute);
            } else {
                $models = $provider->getModels();
                if (($model = reset($models)) instanceof Model) {
                    /* @var $model Model */
                    $label = $model->getAttributeLabel($this->attribute);
                } else {
                    $label = Inflector::camel2words($this->attribute);
                }
            }
        } else {
            $label = $this->label;
        }

        return $label;
    }


    protected function renderBoolean($model, $key, $index)
    {
        $value = \yii\helpers\ArrayHelper::getValue($model, $this->attribute);

        $r = '';

        if($value == 0)
        {
            if($this->stateValue == self::VALUE_GRANTED_BLOCKED 
                    || $this->stateValue == self::VALUE_TRUE_FALSE 
                    )
                $r .= '<span class="badge badge-danger">';
            else
                $r .= '<span class="badge badge-success">';
        }            
        elseif($value == 1)
        {
            if($this->stateValue == self::VALUE_GRANTED_BLOCKED
                    || $this->stateValue == self::VALUE_TRUE_FALSE 
                    )
                $r .= '<span class="badge badge-success">';
            else
                $r .= '<span class="badge badge-danger">';
        }


        switch ($this->stateValue) {
            case 1:
                $r .= ($value == 1) ? Yii::t('app_sys', 'ON') : Yii::t('app_sys', 'OFF');
                break;
            case 2:
                $r .= ($value == 1) ? Yii::t('app_sys', 'ACTIVE') : Yii::t('app_sys', 'OFF');
                break;
            case 3:
                $r .= ($value == 1) ? Yii::t('app_sys', 'SUCCESS') : Yii::t('app_sys', 'ERROR');
                break;
            case 4:
                $r .= ($value == 1) ? Yii::t('app_sys', 'TRUE') : Yii::t('app_sys', 'FALSE');
                break;
            case 5:
                $r .= ($value == 1) ? Yii::t('app_sys', 'GRANTED') : Yii::t('app_sys', 'BLOCKED');
                break;
            case 6:
                $r .= ($value == 1) ? Yii::t('app_sys', '') : Yii::t('app_sys', 'ERROR');
                break;
        }

        $r .= '</span>';

        if(!is_null($value))
            return $r;
    }


    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {

        if ($this->content instanceof Closure) {
            $cell = call_user_func($this->content, $model, $key, $index, $this);
        } else {
            $cell = $this->renderBoolean($model,$key,$index);
        }

        return $cell;

    }

}
?>
