<?php

/**
 * @link http://www.re-soft.de
 * @copyright Copyright (c) Tobias Streckel
 * @license http://www.re-soft.de
 */

namespace strtob\yii2GridviewColumns;

use Yii;
use yii\helpers\Html;
use yii\helpers\Inflector;

class DateColumn extends \yii\grid\Column
{

    private const VALUE_DEFAULT = 1;

    /**
     * {@inheritdoc}
     */
    public $headerOptions = ['class' => 'date-column'];

    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     *
     * Also, if [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    public $attribute;

    /**
     * @var string|null the label for the column. If not set, the label associated with the attribute will be displayed.
     */
    public $label;

    /**
     * @var bool whether the header label should be HTML-encoded.
     * @see label
     * @since 2.0.1
     */
    public $encodeLabel = true;

    /**
     * @var Specific Text; Default = 1
     */
    public $stateValue = self::VALUE_DEFAULT;

    /**
     * @var bool whether to allow sorting by this column. If true and [[attribute]] is found in
     * the sort definition of [[GridView::dataProvider]], then the header cell of this column
     * will contain a link that may trigger the sorting when being clicked.
     */
    public $enableSorting = true;

    /**
     * @var array the HTML attributes for the link tag in the header cell
     * generated by [[\yii\data\Sort::link]] when sorting is enabled for this column.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $sortLinkOptions    = [];
    public $isVisibleAttribute = null;
    public $isVisible          = true;
    public $showTime           = false;

    /**
     * {@inheritdoc}
     */
    protected function renderHeaderCellContent()
    {
        if ($this->header !== null || $this->label === null && $this->attribute === null)
        {
            return parent::renderHeaderCellContent();
        }

        $label = $this->getHeaderCellLabel();

        if ($this->encodeLabel)
        {
            $label = Html::encode($label);
        }

        if ($this->attribute !== null && $this->enableSorting &&
                ($sort = $this->grid->dataProvider->getSort()) !== false && $sort->hasAttribute($this->attribute))
        {
            return $sort->link($this->attribute, array_merge($this->sortLinkOptions, ['label' => $label]));
        }

        return $label;
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    protected function getHeaderCellLabel()
    {
        $provider = $this->grid->dataProvider;

        if ($this->label === null)
        {
            if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface)
            {
                /* @var $modelClass Model */
                $modelClass = $provider->query->modelClass;
                $model      = $modelClass::instance();
                $label      = $model->getAttributeLabel($this->attribute);
            } elseif ($provider instanceof ArrayDataProvider && $provider->modelClass !== null)
            {
                /* @var $modelClass Model */
                $modelClass = $provider->modelClass;
                $model      = $modelClass::instance();
                $label      = $model->getAttributeLabel($this->attribute);
            } elseif ($this->grid->filterModel !== null && $this->grid->filterModel instanceof Model)
            {
                $label = $this->grid->filterModel->getAttributeLabel($this->filterAttribute);
            } else
            {
                $models = $provider->getModels();
                if (($model  = reset($models)) instanceof Model)
                {
                    /* @var $model Model */
                    $label = $model->getAttributeLabel($this->attribute);
                } else
                {
                    $label = Inflector::camel2words($this->attribute);
                }
            }
        } else
        {
            $label = $this->label;
        }

        return $label;
    }

    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        
        if(is_null($model->{$this->attribute}))
            return '';
        
        
        if ($this->isVisibleAttribute)
            $this->isVisible = $model->{$this->isVisibleAttribute};

        if ($this->isVisible)
        {
            $model->{$this->attribute} = yii::$app->formatter->asDate($model->{$this->attribute});

            $r = '';

            if ($this->showTime)
                $r .= Yii::$app->formatter->asDatetime($model->{$this->attribute});
            else
                $r .= Yii::$app->formatter->asDate($model->{$this->attribute});

            if ($r !== '')
            {
                $r .= '<div><small>('
                        . Yii::$app->formatter->asRelativeTime($model->{$this->attribute})
                        . ')</small></div>';
            }

            return $r;
        }
    }
}
