<?php

/**
 * TimestampColumn class file.
 * 
 * This file contains the definition for the TimestampColumn class, which is a part of the 
 * yii2-gridview-columns package. The TimestampColumn class is used to handle and display 
 * timestamp data within a Yii2 GridView widget.
 * 
 * @package yii2-gridview-columns
 * @category GridView
 * @author Tobias Streckel
 * @license MIT
 */

namespace strtob\yii2GridviewColumns;

use Closure;
use yii\base\Model;

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Inflector;
use yii\data\ArrayDataProvider;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQueryInterface;


class TimestampColumn extends \kartik\grid\DataColumn
{

    /**
     * {@inheritdoc}
     */
    public $headerOptions = ['class' => 'timestamp-column'];

    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     *
     * Also, if [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     *
     * Also, if [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    public $attribute;

    /**
     * @var string label to be displayed in the [[header|header cell]] and also to be used as the sorting
     * link label when sorting is enabled for this column.
     * If it is not set and the models provided by the GridViews data provider are instances
     * of [[\yii\db\ActiveRecord]], the label will be determined using [[\yii\db\ActiveRecord::getAttributeLabel()]].
     * Otherwise [[\yii\helpers\Inflector::camel2words()]] will be used to get a label.
     */
    public $label;

    /**
     * @var bool whether the header label should be HTML-encoded.
     * @see label
     * @since 2.0.1
     */
    public $encodeLabel = true;


    /**
     * @var bool whether to allow sorting by this column. If true and [[attribute]] is found in
     * the sort definition of [[GridView::dataProvider]], then the header cell of this column
     * will contain a link that may trigger the sorting when being clicked.
     */
    public $enableSorting = true;

    /**
     * @var array the HTML attributes for the link tag in the header cell
     * generated by [[\yii\data\Sort::link]] when sorting is enabled for this column.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $sortLinkOptions = [];



    /**
     * @inheritdoc
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {

        $this->filterType = GridView::FILTER_DATE_RANGE;
        //$this->filter = \yii\helpers\ArrayHelper::map(\app\models\sys\LogAuthType::find()->asArray()->all(), 'id', 'name');
        $this->filterWidgetOptions = [
            'attribute' => 'updated_at',
            'presetDropdown' => true,
            'convertFormat' => false,
            'pluginOptions' => [
                'separator' => '.',
                'format' => 'DD.MM.YYYY',
                'locale' => [
                    'format' => 'DD.MM.YYYY'
                ]
            ]
        ];
        //$this->filterInputOptions  = ['placeholder' => '', 'id' => 'grid-log-auth-search-tbl_sys_log_auth_type_id'];

        parent::init();
    }


    /**
     * {@inheritdoc}
     */
    protected function renderHeaderCellContent()
    {
        if ($this->header !== null || $this->label === null && $this->attribute === null) {
            return parent::renderHeaderCellContent();
        }

        $label = $this->getHeaderCellLabel();
        if ($this->encodeLabel) {
            $label = Html::encode($label);
        }

        if (
            $this->attribute !== null && $this->enableSorting &&
            ($sort = $this->grid->dataProvider->getSort()) !== false && $sort->hasAttribute($this->attribute)
        ) {
            return $sort->link($this->attribute, array_merge($this->sortLinkOptions, ['label' => $label]));
        }

        return $label;
    }

    /**
     * {@inheritdoc}
     * @since 2.0.8
     */
    protected function getHeaderCellLabel()
    {
        $provider = $this->grid->dataProvider;

        if ($this->label === null) {
            if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface) {
                /* @var $modelClass Model */
                $modelClass = $provider->query->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($provider instanceof ArrayDataProvider && $provider->modelClass !== null) {
                /* @var $modelClass Model */
                $modelClass = $provider->modelClass;
                $model = $modelClass::instance();
                $label = $model->getAttributeLabel($this->attribute);
            } elseif ($this->grid->filterModel !== null && $this->grid->filterModel instanceof Model) {
                $label = $this->grid->filterModel->getAttributeLabel($this->filterAttribute);
            } else {
                $models = $provider->getModels();
                if (($model = reset($models)) instanceof Model) {
                    /* @var $model Model */
                    $label = $model->getAttributeLabel($this->attribute);
                } else {
                    $label = Inflector::camel2words($this->attribute);
                }
            }
        } else {
            $label = $this->label;
        }

        return $label;
    }


    protected function renderTimestamp($model, $key, $index)
    {

        $timestamp = \yii\helpers\ArrayHelper::getValue($model, $this->attribute);

        $relativeTime = \Yii::$app->formatter->asRelativeTime($timestamp, 'now');

        $d1 = null;

        if (!$this->isValidTimeStamp($timestamp)) {
            $d1 = new \DateTime();
            $d1->setTimestamp(strtotime($timestamp));
        } else {
            $d1 = new \DateTime($timestamp);
        }


        $d2 = new \DateTime(date('m/d/Y h:i:s a', time()));
        $interval = $d1->diff($d2);
        $hours = $interval->format('%h');


        $r = \Yii::$app->formatter->asDatetime($timestamp);
        $r .= '<h6><span class="badge badge-';

        if ($hours <= 24) {
            $r .= 'primary';
        } elseif ($hours > 24 && $hours <= 72) {
            $r .= 'success';
        } elseif ($hours > 72) {
            $r .= 'info';
        }

        $r .= '">';
        $r .= $relativeTime;
        $r .= '</span></h6>';

        return $r;
    }

    private function isValidTimeStamp($timestamp)
    {
        return ((string) (int) $timestamp === $timestamp)
            && ($timestamp <= PHP_INT_MAX)
            && ($timestamp >= ~PHP_INT_MAX);
    }


    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {

        if ($this->content instanceof Closure) {
            $cell = call_user_func($this->content, $model, $key, $index, $this);
        } else {
            $cell = $this->renderTimestamp($model, $key, $index);
        }

        return $cell;

    }

}
?>