<?php

/**
 * @link http://www.re-soft.de
 * @copyright Copyright (c) Tobias Streckel
 * @license http://www.re-soft.de
 */

namespace strtob\yii2GridviewColumns;

use Yii;
use yii\helpers\Html;
use yii\helpers\Inflector;

class UserColumn extends \yii\grid\Column
{

    /**
     * {@inheritdoc}
     */
    public $headerOptions = ['class' => 'data-col-user-image-column-header'];

    /**
     * @var string the attribute name associated with this column. When neither [[content]] nor [[value]]
     * is specified, the value of the specified attribute will be retrieved from each data model and displayed.
     *
     * Also, if [[label]] is not specified, the label associated with the attribute will be displayed.
     */
    public $attribute;

    /**
     * @var string|null the label for the column. If not set, the label associated with the attribute will be displayed.
     */
    public $label = '';

    /**
     * @var \Closure|null the value to be displayed in each data cell. 
     * If a closure is provided, it will be executed for each data model to retrieve the value.
     * If not set, the column will retrieve the value from the specified attribute of each data model.
     */
    public $value;

    /**
     * @var string|null the format to be applied to the value of each data cell.
     * If not set, no formatting will be applied. This can be a string representing a
     * PHP date format or any other format accepted by the `yii\i18n\Formatter` class.
     */
    public $format = 'html';

    /**
     * @var bool whether the header label should be HTML-encoded.
     * @see label
     * @since 2.0.1
     */
    public $encodeLabel = true;

    /**
     * @var bool whether to allow sorting by this column. If true and [[attribute]] is found in
     * the sort definition of [[GridView::dataProvider]], then the header cell of this column
     * will contain a link that may trigger the sorting when being clicked.
     */
    public $enableSorting = true;

    /**
     * @var array the HTML attributes for the link tag in the header cell
     * generated by [[\yii\data\Sort::link]] when sorting is enabled for this column.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $sortLinkOptions = [];

    /**
     * {@inheritdoc}
     */
    protected function renderHeaderCellContent()
    {
        $label = $this->getHeaderCellLabel();

        if ($this->encodeLabel)
        {
            $label = Html::encode($label);
        }

        // Check if $label is empty and set a default label
        $label = yii::t('app', 'User');

        // Add your custom label or additional content to the header cell
        $headerContent = '<div class="custom-header">' . $label . '</div>';

        return $headerContent;
    }

    /**
     * {@inheritdoc}
     */

    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $value = $this->value;

        if ($value instanceof \Closure)
        {
            $value = call_user_func($value, $model, $index);
        } else
        {
            $value = $model->{$this->attribute};
        }

        $modelUser = \backend\components\modules\admin\models\User::findOne($value);

        if ($modelUser && $modelUser->profile)
        {
            $r = '';

            $contentOptions = $this->getContentOptions($model, $key, $index);

            $r .= '<div class="row"' . Html::renderTagAttributes($contentOptions) . '>';

            $r .= '<div class="col-auto">';

            if ($modelUser)
            {
                $image = $modelUser->getUserImageUrl();
                $r     .= Html::img($image, ['class' => 'avatar-sm rounded']);
            }

            $r .= '</div>';

            $r .= '<div class="col-6">';

            $r .= '<h6 class="comment-createor-fullname fs-14 mb-0">';

            $r .= $modelUser->profile->last_name . ', ' . $modelUser->profile->first_name;

            $r .= '</h6>';
            $r .= '<p class="text-uppercase"> ';
            $r .= $modelUser->profile->designation;
            $r .= '</p>';
            $r .= '</div>';

            $r .= '</div>';

            return $r;
        }
    }

    /**
     * Returns the HTML attributes for the content options.
     * @param mixed $model the data model being rendered
     * @param string $key the key associated with the data model
     * @param int $index the zero-based index of the data model among the models array returned by [[dataProvider]].
     * @return array the HTML attributes for the content options.
     */
    protected function getContentOptions($model, $key, $index)
    {
        $options = $this->contentOptions;
        if ($options instanceof \Closure)
        {
            $options = call_user_func($options, $model, $key, $index, $this);
        }
        return $options;
    }
}
